image: python:3.9

stages:
  - build
  - test

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache: &global_cache
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/pip
    - venv/
  policy: pull-push


build:
  stage: build
  script:
    - make -B virtual-environment


# Test the rcmip package and CLI
test: &test_config
  stage: test
  cache:
    <<: *global_cache
    policy: pull  # only pull from cache
  before_script:
    - source venv/bin/activate
  script:
    - pip freeze
    # Ignore tests/notebooks as that is covered by test:notebooks
    - pytest --cov bookshelf -rfsxEX --cov-report term-missing --junitxml=report.xml --ignore=tests/notebooks
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

test:notebooks:
  <<: *test_config
  variables:
    BOOKSHELF_CACHE_LOCATION: out
  script:
    - pytest tests/notebooks --log-cli-level INFO
  artifacts:
    when: always
    paths:
      - out
    expire_in: 1 week

test:format:
  <<: *test_config
  script:
    - flake8 setup.py src tests notebooks
    - black --check src tests notebooks
    - mypy --install-types --non-interactive src
    - pylint --fail-under=9.5 src
    - bandit -r src
