target-version = "py310"
line-length = 110

[lint]
select = [
    "E",
    "W",
    "F",
    "I",
    "D",
    "PL",
    "NPY",
    "RUF",
    "UP",
    "S",
]
unfixable = [
    "PD002",
]
ignore = [
    "D100",
    "D105", # Missing docstring in magic method
    "D200",
    "D400",
    "UP007",
]

[lint.per-file-ignores]
"test*.py" = [
    "D",  # Documentation not needed in tests
    "S101",  # S101 Use of `assert` detected
    "PLR2004" # Magic value used in comparison
]
"conftest.py" = [
    "D",  # Documentation not needed in tests
    "S101",  # S101 Use of `assert` detected
    "PLR2004" # Magic value used in comparison
]
"docs/*" = [
    "D100",  # Missing docstring at the top of file
    "E402",  # Module level import not at top of file
    "S101",  # Use of `assert` detected
]
"notebooks/*" = [
    "D100",  # Missing docstring at the top of file
    "D103",  # Missing docstring in public function
    "E402",  # Module level import not at top of file
    "S101",  # Use of `assert` detected
    "PD901",  # `df` is a bad variable name.
]
"scripts/*" = [
    "S101" # S101 Use of `assert` detected
]

[lint.isort]
known-first-party = ["bookshelf", "bookshelf_producer"]

[lint.pydocstyle]
convention = "numpy"

[format]
docstring-code-format = true
