#!/usr/bin/env python3
"""Generate the committed Pydantic model core from the vendored OpenAPI document."""

from __future__ import annotations

import json
import py_compile
import secrets
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Callable, Sequence
from pathlib import Path
from typing import NoReturn

SDK_ROOT = Path(__file__).resolve().parents[1]
PACKAGE_ROOT = SDK_ROOT / "src" / "bookshelf"
LIVE_TREE = PACKAGE_ROOT / "_generated"
OPENAPI_PATH = SDK_ROOT / "openapi.json"
EXPECTED_MANIFEST = {"__init__.py", "models.py"}
DATAMODEL_CODE_GENERATOR_VERSION = "0.68.1"
RUFF_VERSION = "0.15.0"

Hook = Callable[[str], None]
Runner = Callable[[str, Sequence[str]], subprocess.CompletedProcess[str]]


class GenerationError(RuntimeError):
    """A fail-closed generation or recovery error."""


def _default_hook(_boundary: str) -> None:
    return None


def _default_runner(boundary: str, command: Sequence[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(command, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as exc:
        output = "\n".join(part for part in (exc.stdout, exc.stderr) if part)
        raise GenerationError(f"{boundary} failed\n{output}".rstrip()) from exc


def _stop(message: str) -> NoReturn:
    raise GenerationError(f"STOP: {message}")


def _header(version: str) -> str:
    return (
        "# DO NOT EDIT: generated by packages/bookshelf/scripts/generate_models.py.\n"
        "# Source: openapi.json\n"
        f"# OPENAPI_VERSION: {version}\n"
    )


def _load_contract(path: Path) -> tuple[dict[str, object], str]:
    try:
        value = json.loads(path.read_text())
    except (OSError, json.JSONDecodeError) as exc:
        raise GenerationError(f"Cannot read valid JSON from {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise GenerationError("openapi.json must contain a JSON object")
    if value.get("openapi") != "3.1.0":
        raise GenerationError('openapi.json must declare openapi == "3.1.0"')
    info = value.get("info")
    if not isinstance(info, dict):
        raise GenerationError("openapi.json must contain an info object")
    version = info.get("version")
    if not isinstance(version, str) or not version.strip():
        raise GenerationError("openapi.json info.version must be a non-blank string")
    components = value.get("components")
    schemas = components.get("schemas") if isinstance(components, dict) else None
    if not isinstance(schemas, dict) or not schemas:
        raise GenerationError("openapi.json components.schemas must be a non-empty object")
    return value, version


class TreeValidator:
    """Validate an exact generated tree without importing it into this process."""

    def __init__(self, version: str | None, runner: Runner = _default_runner) -> None:
        self.version = version
        self.runner = runner

    @staticmethod
    def _embedded_version(tree: Path) -> str:
        versions: set[str] = set()
        prefix = "# OPENAPI_VERSION: "
        for relative in sorted(EXPECTED_MANIFEST):
            matches = [
                line.removeprefix(prefix).strip()
                for line in (tree / relative).read_text().splitlines()[:10]
                if line.startswith(prefix)
            ]
            if len(matches) != 1 or not matches[0]:
                raise GenerationError(f"Missing embedded OpenAPI version in {tree / relative}")
            versions.add(matches[0])
        if len(versions) != 1:
            raise GenerationError(
                f"Inconsistent embedded OpenAPI versions in {tree}: {sorted(versions)}"
            )
        return versions.pop()

    def __call__(self, tree: Path, *, boundary: str = "tree-validation") -> None:
        if not tree.is_dir():
            raise GenerationError(f"{tree} is not a directory")
        # Runtime imports may leave ignored bytecode caches in an otherwise valid
        # committed tree. They are never authoritative generated output and are
        # discarded with the old live tree after a successful promotion.
        entries = [
            path for path in tree.rglob("*") if "__pycache__" not in path.relative_to(tree).parts
        ]
        manifest = {path.relative_to(tree).as_posix() for path in entries if path.is_file()}
        directories = [path.relative_to(tree).as_posix() for path in entries if path.is_dir()]
        if manifest != EXPECTED_MANIFEST or directories:
            raise GenerationError(
                f"Unexpected generated manifest at {tree}: files={sorted(manifest)}, "
                f"directories={sorted(directories)}"
            )
        version = self.version or self._embedded_version(tree)
        expected_header = _header(version)
        for relative in sorted(EXPECTED_MANIFEST):
            path = tree / relative
            text = path.read_text()
            if not text.startswith(expected_header):
                raise GenerationError(f"Missing deterministic header in {path}")
            header_lines = "\n".join(text.splitlines()[:10]).lower()
            if "timestamp" in header_lines or "generated at" in header_lines:
                raise GenerationError(f"Wall-clock timestamp found in {path}")
            if str(SDK_ROOT) in text or str(SDK_ROOT.parent) in text:
                raise GenerationError(f"Absolute project path found in {path}")

        with tempfile.TemporaryDirectory(prefix=".generated.compile.", dir=PACKAGE_ROOT) as tmp:
            for relative in sorted(EXPECTED_MANIFEST):
                try:
                    py_compile.compile(
                        str(tree / relative),
                        cfile=str(Path(tmp) / f"{relative}.pyc"),
                        doraise=True,
                    )
                except py_compile.PyCompileError as exc:
                    raise GenerationError(
                        f"Syntax compilation failed for {relative}: {exc}"
                    ) from exc

        smoke = """
import importlib.util
import pathlib
import sys

tree = pathlib.Path(sys.argv[1])
expected = sys.argv[2]
name = "_bookshelf_generated_validation"
spec = importlib.util.spec_from_file_location(
    name, tree / "__init__.py", submodule_search_locations=[str(tree)]
)
assert spec is not None and spec.loader is not None
module = importlib.util.module_from_spec(spec)
sys.modules[name] = module
spec.loader.exec_module(module)
assert module.OPENAPI_VERSION == expected
assert module.models
"""
        self.runner(
            f"{boundary}:isolated-import",
            [sys.executable, "-B", "-c", smoke, str(tree), version],
        )


def _siblings(prefix: str) -> list[Path]:
    return sorted(PACKAGE_ROOT.glob(prefix), key=lambda path: path.name)


def _remove_tree(path: Path, hook: Hook, boundary: str) -> None:
    hook(f"before_{boundary}")
    shutil.rmtree(path)
    hook(f"after_{boundary}")


def _rename(source: Path, destination: Path, hook: Hook, boundary: str) -> None:
    hook(f"before_{boundary}")
    source.rename(destination)
    hook(f"after_{boundary}")


def _normal_state(_version: str, runner: Runner, hook: Hook) -> None:
    """Recover startup residue conservatively, then remove abandoned temporary trees."""
    validator = TreeValidator(None, runner)
    backups = _siblings("._generated.backup.*")
    temporary = _siblings("._generated.tmp.*")
    print(
        "Recovery state: "
        f"live={'present' if LIVE_TREE.exists() else 'absent'}, "
        f"backups={len(backups)}, temporary={len(temporary)}"
    )
    if len(backups) > 1:
        _stop("multiple backup trees exist. Preserving all generated-tree evidence")

    if len(backups) == 1:
        backup = backups[0]
        if not LIVE_TREE.exists():
            try:
                validator(backup, boundary="startup-backup")
                _rename(backup, LIVE_TREE, hook, "startup_backup_to_live")
            except Exception as exc:
                _stop(f"sole backup could not be restored. Preserving all evidence: {exc}")
        else:
            try:
                validator(LIVE_TREE, boundary="startup-live")
            except Exception as exc:
                _stop(
                    f"live and backup coexist but live is invalid. Preserving all evidence: {exc}"
                )
            try:
                _remove_tree(backup, hook, "startup_backup_cleanup")
            except Exception as exc:
                _stop(f"valid live tree retained but backup cleanup failed: {exc}")

    if not _siblings("._generated.backup.*") and LIVE_TREE.exists():
        try:
            validator(LIVE_TREE, boundary="startup-live")
        except Exception as exc:
            _stop(f"live generated tree is invalid, refusing destructive repair: {exc}")

    if _siblings("._generated.backup.*"):
        _stop("backup residue remains after startup recovery")
    for tree in _siblings("._generated.tmp.*"):
        try:
            _remove_tree(tree, hook, "startup_temporary_cleanup")
        except Exception as exc:
            _stop(f"abandoned temporary tree cleanup failed: {exc}")


def _unique_tree(kind: str) -> Path:
    while True:
        path = PACKAGE_ROOT / f"._generated.{kind}.{secrets.token_hex(12)}"
        try:
            path.mkdir(mode=0o700)
        except FileExistsError:
            continue
        return path


def _tool_version(name: str, expected: str, runner: Runner, command: Sequence[str]) -> None:
    completed = runner(f"{name}-version", command)
    output = "\n".join(part for part in (completed.stdout, completed.stderr) if part).strip()
    if expected not in output:
        raise GenerationError(f"Expected {name} {expected}, got: {output}")
    print(output)


def _write_initializer(tree: Path, version: str) -> None:
    (tree / "__init__.py").write_text(
        _header(version)
        + "\nfrom . import models as models\n\n"
        + f'OPENAPI_VERSION = "{version}"\n\n'
        + '__all__ = ["OPENAPI_VERSION", "models"]\n'
    )


def _generate_temporary(tree: Path, version: str, runner: Runner) -> None:
    models_path = tree / "models.py"
    runner(
        "datamodel-codegen",
        [
            "datamodel-codegen",
            "--input",
            str(OPENAPI_PATH),
            "--input-file-type",
            "openapi",
            "--schema-version",
            "3.1",
            "--schema-version-mode",
            "strict",
            "--openapi-scopes",
            "schemas",
            "--output-model-type",
            "pydantic_v2.BaseModel",
            "--target-python-version",
            "3.12",
            "--disable-timestamp",
            "--formatters",
            "builtin",
            "--use-annotated",
            "--set-default-enum-member",
            "--output",
            str(models_path),
        ],
    )
    if not models_path.is_file():
        raise GenerationError("datamodel-codegen did not create models.py")
    models_path.write_text(_header(version) + "\n" + models_path.read_text())
    _write_initializer(tree, version)
    runner("ruff-check", ["ruff", "check", "--fix", str(tree)])
    runner("ruff-format", ["ruff", "format", str(tree)])


def _pre_promotion_check(own_tree: Path, validator: TreeValidator) -> bool:
    backups = _siblings("._generated.backup.*")
    temporary = _siblings("._generated.tmp.*")
    if backups or temporary != [own_tree]:
        _stop(
            "generated-tree state changed before promotion. Preserving all observed state "
            f"(backups={[p.name for p in backups]}, temporary={[p.name for p in temporary]})"
        )
    live_exists = LIVE_TREE.exists()
    if live_exists:
        TreeValidator(None, validator.runner)(LIVE_TREE, boundary="pre-promotion-live")
    return live_exists


def _cleanup_owned_temporary(tree: Path, hook: Hook) -> None:
    if tree.exists():
        _remove_tree(tree, hook, "owned_temporary_cleanup")


def _rollback(
    temporary: Path,
    backup: Path,
    validator: TreeValidator,
    hook: Hook,
    *,
    candidate_is_live: bool,
) -> None:
    """Restore the previous live tree or raise while preserving remaining evidence."""
    try:
        if candidate_is_live and LIVE_TREE.exists():
            _rename(LIVE_TREE, temporary, hook, "rollback_candidate_to_temporary")
        if not backup.exists() or LIVE_TREE.exists():
            _stop("rollback state is ambiguous before backup restoration")
        _rename(backup, LIVE_TREE, hook, "rollback_backup_to_live")
        TreeValidator(None, validator.runner)(LIVE_TREE, boundary="rollback-live")
        _cleanup_owned_temporary(temporary, hook)
    except Exception as exc:
        _stop(f"rollback failed or became ambiguous. Preserving remaining evidence: {exc}")


def _promote(
    temporary: Path,
    live_exists: bool,
    validator: TreeValidator,
    hook: Hook,
) -> None:
    if not live_exists:
        try:
            _rename(temporary, LIVE_TREE, hook, "temporary_to_live")
            hook("before_post_promotion_validation")
            validator(LIVE_TREE, boundary="post-promotion-live")
            hook("after_post_promotion_validation")
        except Exception as exc:
            try:
                if LIVE_TREE.exists() and not temporary.exists():
                    _rename(LIVE_TREE, temporary, hook, "failed_first_live_to_temporary")
                _cleanup_owned_temporary(temporary, hook)
            except Exception as rollback_exc:
                _stop(
                    "first-generation promotion failed and candidate cleanup was ambiguous: "
                    f"{exc}, cleanup: {rollback_exc}"
                )
            raise GenerationError(f"First-generation promotion failed: {exc}") from exc
        return

    backup = _unique_tree("backup")
    backup.rmdir()
    moved_live = False
    candidate_is_live = False
    try:
        _rename(LIVE_TREE, backup, hook, "live_to_backup")
        moved_live = True
        _rename(temporary, LIVE_TREE, hook, "temporary_to_live")
        candidate_is_live = True
        hook("before_post_promotion_validation")
        validator(LIVE_TREE, boundary="post-promotion-live")
        hook("after_post_promotion_validation")
    except Exception as exc:
        # A fault injected immediately after a rename observes the new filesystem
        # state before the assignment following `_rename` can run. Classify the
        # paths themselves so both sides of each rename boundary are recoverable.
        moved_live = moved_live or backup.exists()
        candidate_is_live = candidate_is_live or (LIVE_TREE.exists() and not temporary.exists())
        if moved_live:
            _rollback(
                temporary,
                backup,
                validator,
                hook,
                candidate_is_live=candidate_is_live,
            )
        else:
            _cleanup_owned_temporary(temporary, hook)
        raise GenerationError(f"Promotion failed: previous generated tree restored: {exc}") from exc

    try:
        _remove_tree(backup, hook, "backup_cleanup")
    except Exception as exc:
        _stop(
            "promoted live is valid but backup cleanup failed. Preserving remaining backup "
            f"evidence, which may be partial once cleanup starts: {exc}"
        )


def generate(*, runner: Runner = _default_runner, hook: Hook = _default_hook) -> None:
    """Run validated generation and conservative promotion."""
    PACKAGE_ROOT.mkdir(parents=True, exist_ok=True)
    _contract, version = _load_contract(OPENAPI_PATH)
    print("Input: openapi.json")
    print("Output: src/bookshelf/_generated")
    print(f"OPENAPI_VERSION={version}")
    _normal_state(version, runner, hook)
    _tool_version(
        "datamodel-code-generator",
        DATAMODEL_CODE_GENERATOR_VERSION,
        runner,
        ["datamodel-codegen", "--version"],
    )
    _tool_version("ruff", RUFF_VERSION, runner, ["ruff", "--version"])

    temporary = _unique_tree("tmp")
    validator = TreeValidator(version, runner)
    try:
        _generate_temporary(temporary, version, runner)
        validator(temporary, boundary="temporary")
    except Exception:
        try:
            _cleanup_owned_temporary(temporary, hook)
        except Exception as cleanup_exc:
            _stop(f"generation failed and its temporary tree could not be cleaned: {cleanup_exc}")
        raise

    live_exists = _pre_promotion_check(temporary, validator)
    _promote(temporary, live_exists, validator, hook)
    if _siblings("._generated.tmp.*") or _siblings("._generated.backup.*"):
        _stop("successful promotion left temporary or backup residue")
    print("Generated src/bookshelf/_generated from openapi.json")


def main() -> int:
    try:
        generate()
    except (GenerationError, OSError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
