#!/usr/bin/env python3
"""Generate the mechanical operation methods on ``BookshelfClient``.

The source of truth is the ``build_*``/``parse_*`` function pairs in
``bookshelf/_core/ops.py``, discovered by name.
Those signatures already carry the method name, the fully typed parameter list,
the defaults and the return type,
so restating any of that in ``OP_REGISTRY`` would create a second source of truth
that can drift from the functions that actually execute.

``OP_REGISTRY`` still has a job here.
It is the only place that knows the complete set of operations the API offers,
so it gates coverage: every registry entry must reach a client method.

Annotation and default text is read from the ``ops.py`` AST with :func:`ast.unparse`
rather than from :func:`inspect.signature`,
because ``inspect`` renders resolved objects and would turn ``DataFormat`` into its
expanded ``Literal`` and ``UUID`` into ``uuid.UUID``.
:func:`inspect.signature` is kept as a hard cross-check that the structure has not drifted.
"""

import ast
import inspect
import subprocess
import sys
from collections.abc import Sequence
from pathlib import Path
from types import ModuleType

SDK_ROOT = Path(__file__).resolve().parents[1]
OPS_PATH = SDK_ROOT / "src" / "bookshelf" / "_core" / "ops.py"
CLIENT_PATH = SDK_ROOT / "src" / "bookshelf" / "_core" / "client.py"
RUFF_VERSION = "0.15.0"

MARKER = "    # --- BEGIN GENERATED OPERATIONS ---"
HEADER = f"""{MARKER}
    # Generated by packages/bookshelf/scripts/generate_client.py
    # from the build_*/parse_* pairs in bookshelf/_core/ops.py.
    # Everything below this line is overwritten on every run, so never edit it by hand.
    # To add an operation, add its build_*/parse_* pair to ops.py and regenerate.
"""

# Operations in OP_REGISTRY that the client deliberately does not expose.
# Each entry needs a reason. The coverage assertion fails on anything not listed here.
UNIMPLEMENTED_OPERATIONS: dict[str, str] = {}


class GenerationError(RuntimeError):
    """A fail-closed generation error."""


def _run(boundary: str, command: Sequence[str]) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(command, check=True, capture_output=True, text=True)
    except subprocess.CalledProcessError as exc:
        output = "\n".join(part for part in (exc.stdout, exc.stderr) if part)
        raise GenerationError(f"{boundary} failed\n{output}".rstrip()) from exc


def _tool_version(name: str, expected: str, command: Sequence[str]) -> None:
    completed = _run(f"{name}-version", command)
    output = "\n".join(part for part in (completed.stdout, completed.stderr) if part).strip()
    if expected not in output:
        raise GenerationError(f"Expected {name} {expected}, got: {output}")
    print(output)


def _functions(tree: ast.Module, prefix: str) -> dict[str, ast.FunctionDef]:
    return {
        node.name.removeprefix(prefix): node
        for node in tree.body
        if isinstance(node, ast.FunctionDef) and node.name.startswith(prefix)
    }


def _signature_text(node: ast.FunctionDef) -> str:
    """Render the build function's parameters as they appear in the source."""
    parts: list[str] = []
    positional = node.args.posonlyargs + node.args.args
    defaults: list[ast.expr | None] = [None] * (len(positional) - len(node.args.defaults))
    defaults.extend(node.args.defaults)
    for arg, default in zip(positional, defaults, strict=True):
        parts.append(_parameter_text(arg, default))
    if node.args.kwonlyargs:
        parts.append("*")
        for arg, kw_default in zip(node.args.kwonlyargs, node.args.kw_defaults, strict=True):
            parts.append(_parameter_text(arg, kw_default))
    return "".join(f", {part}" for part in parts)


def _parameter_text(arg: ast.arg, default: ast.expr | None) -> str:
    if arg.annotation is None:
        raise GenerationError(f"Parameter {arg.arg} is unannotated")
    text = f"{arg.arg}: {ast.unparse(arg.annotation)}"
    if default is not None:
        text = f"{text} = {ast.unparse(default)}"
    return text


def _call_arguments(node: ast.FunctionDef) -> str:
    positional = [arg.arg for arg in node.args.posonlyargs + node.args.args]
    keyword = [f"{arg.arg}={arg.arg}" for arg in node.args.kwonlyargs]
    return ", ".join(positional + keyword)


def _cross_check(operation: str, node: ast.FunctionDef, ops_module: ModuleType) -> None:
    """Fail on any structural drift between the AST reading and the live function."""
    live = inspect.signature(getattr(ops_module, f"build_{operation}"))
    expected = [
        (arg.arg, inspect.Parameter.POSITIONAL_OR_KEYWORD)
        for arg in node.args.posonlyargs + node.args.args
    ] + [(arg.arg, inspect.Parameter.KEYWORD_ONLY) for arg in node.args.kwonlyargs]
    actual = [(name, parameter.kind) for name, parameter in live.parameters.items()]
    if expected != actual:
        raise GenerationError(
            f"build_{operation} parameters drifted between the AST and inspect: "
            f"ast={expected}, inspect={actual}"
        )


def _render(operation: str, build: ast.FunctionDef, parse: ast.FunctionDef) -> str:
    if parse.returns is None:
        raise GenerationError(f"parse_{operation} has no return annotation")
    returns = ast.unparse(parse.returns)
    signature = _signature_text(build)
    arguments = _call_arguments(build)
    # A parse that returns None is called for its side effect of raising, so it is a statement.
    keyword = "" if returns == "None" else "return "
    call = f"ops.build_{operation}({arguments})"
    return (
        f"    def {operation}(self{signature}) -> {returns}:\n"
        f"        {keyword}ops.parse_{operation}(self._send({call}))\n"
        "\n"
        f"    async def {operation}_async(self{signature}) -> {returns}:\n"
        f"        {keyword}ops.parse_{operation}(await self._send_async({call}))\n"
    )


def _preserved_region(text: str) -> str:
    lines = text.splitlines(keepends=True)
    starts = [index for index, line in enumerate(lines) if line.rstrip("\n") == MARKER]
    if len(starts) != 1:
        raise GenerationError(
            f"Expected exactly one {MARKER.strip()!r} line in {CLIENT_PATH}, found {len(starts)}"
        )
    return "".join(lines[: starts[0]])


def _defined_methods(text: str) -> set[str]:
    return {
        node.name
        for parent in ast.walk(ast.parse(text))
        if isinstance(parent, ast.ClassDef)
        for node in parent.body
        if isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef)
    }


def _assert_coverage(ops_module: ModuleType, tree: ast.Module, methods: set[str]) -> None:
    """Every operation the API offers must reach a client method, or be listed as deferred."""
    specs = {
        name: value
        for name, value in vars(ops_module).items()
        if isinstance(value, ops_module.OpSpec)
    }
    reached: dict[str, str] = {}
    for operation, node in _functions(tree, "build_").items():
        for descendant in ast.walk(node):
            if isinstance(descendant, ast.Name) and descendant.id in specs:
                reached[specs[descendant.id].operation_id] = operation
    missing = {
        operation_id: reached.get(operation_id)
        for operation_id in ops_module.OP_REGISTRY
        if reached.get(operation_id) not in methods
    }
    unlisted = sorted(set(missing) - set(UNIMPLEMENTED_OPERATIONS))
    if unlisted:
        raise GenerationError(
            "OP_REGISTRY operations have no client method and are not on the deferred "
            f"allow-list: {unlisted}"
        )
    stale = sorted(set(UNIMPLEMENTED_OPERATIONS) - set(missing))
    if stale:
        raise GenerationError(f"Deferred allow-list entries are now implemented: {stale}")
    print(f"Coverage: {len(ops_module.OP_REGISTRY)} registry operations, {len(missing)} deferred")


def generate() -> None:
    """Regenerate the client's operation region in place."""
    _tool_version("ruff", RUFF_VERSION, ["ruff", "--version"])
    from bookshelf._core import ops as ops_module

    tree = ast.parse(OPS_PATH.read_text())
    builds = _functions(tree, "build_")
    parses = _functions(tree, "parse_")
    client_text = CLIENT_PATH.read_text()
    preserved = _preserved_region(client_text)
    hand_written = _defined_methods(preserved)

    rendered: list[str] = []
    # Sorted so that inserting an operation in the middle of ops.py cannot reshuffle the output.
    for operation in sorted(builds.keys() & parses.keys()):
        if operation in hand_written:
            continue
        _cross_check(operation, builds[operation], ops_module)
        rendered.append(_render(operation, builds[operation], parses[operation]))

    generated = preserved + HEADER + "\n" + "\n".join(rendered)
    try:
        ast.parse(generated)
    except SyntaxError as exc:
        raise GenerationError(f"Generated client.py does not parse: {exc}") from exc

    _assert_coverage(ops_module, tree, _defined_methods(generated))

    CLIENT_PATH.write_text(generated)
    _run("ruff-check", ["ruff", "check", "--fix", str(CLIENT_PATH)])
    _run("ruff-format", ["ruff", "format", str(CLIENT_PATH)])
    print(f"Generated {len(rendered)} operation method pairs in {CLIENT_PATH.name}")


def main() -> int:
    try:
        generate()
    except (GenerationError, OSError) as exc:
        print(str(exc), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
