# DO NOT EDIT: generated by packages/bookshelf/scripts/generate_models.py.
# Source: openapi.json
# OPENAPI_VERSION: 1.0.2.dev47+g7fc6f93c

from . import models as models

OPENAPI_VERSION = "1.0.2.dev47+g7fc6f93c"

__all__ = ["OPENAPI_VERSION", "models"]
