# DO NOT EDIT: generated by packages/bookshelf/scripts/generate_models.py.
# Source: openapi.json
# OPENAPI_VERSION: 1.0.2.dev18+ge7de4f37

from . import models as models

OPENAPI_VERSION = "1.0.2.dev18+ge7de4f37"

__all__ = ["OPENAPI_VERSION", "models"]
