# DO NOT EDIT: generated by packages/bookshelf/scripts/generate_models.py.
# Source: openapi.json
# OPENAPI_VERSION: 0.3.1.dev592+ga380ada4

from . import models as models

OPENAPI_VERSION = "0.3.1.dev592+ga380ada4"

__all__ = ["OPENAPI_VERSION", "models"]
