"""Registering a method card as the plan its activity followed, with ``register(..., role="plan")``.

A plan is not an output: it is neither generated by the activity nor derived from its inputs.
"""

import json
from pathlib import Path
from typing import Any
from unittest.mock import Mock

import httpx
import pytest

from bookshelf._core.client import BookshelfClient
from bookshelf.cache import ContentCache
from bookshelf.facade import AsyncBookshelf, Bookshelf
from bookshelf.publisher.bundle import Bundle, InvalidBundleError
from bookshelf.publisher.recording import RecordingSink
from bookshelf.publisher.replay import replay_bundle, replay_bundle_sync
from tests import _core_payloads as payloads
from tests._replay import BASE_URL, replay_client, replayed

CARD_ID = "0197a000-0000-7000-8000-00000000c0de"


def _record_plan_bundle(tmp_path: Path) -> Bundle:
    bundle = Bundle(tmp_path / "bundle")
    sink = RecordingSink(bundle, Mock(spec=BookshelfClient), ContentCache(tmp_path / "cache"))
    forcing = sink.register_external(
        type="tabular", uri="https://example.invalid/forcing.csv", name="forcing"
    )
    with sink.activity(code_ref="repo@sha", config={}) as activity:
        activity.register(b"alpha", type="document", name="alpha", used=[forcing])
        activity.register(b"method", type="document", name="method-card", role="plan")
        activity.register(b"beta", type="document", name="beta")
    bundle.write()
    return bundle


def test_a_recorded_plan_replays_as_the_activity_plan(tmp_path: Path) -> None:
    bundle = _record_plan_bundle(tmp_path)
    recorded: list[httpx.Request] = []

    with replay_client(recorded) as client:
        replay_bundle_sync(bundle, client)

    resources = {resource["name"]: resource for resource in replayed(recorded)["resources"]}
    card = resources["method-card"]
    assert card["role"] == "plan"
    assert card["generated"] is False
    assert card["used"] == []
    assert resources["beta"]["used"] == ["forcing"]
    assert "role" not in resources["beta"]


def _registered(tracking_id: str) -> dict[str, Any]:
    return {
        "activity_created": False,
        "atomic": True,
        "registered": [
            {
                "index": 0,
                "status": "created",
                "outcome": {"status": "created", "tracking_id": tracking_id, "dedupe": True},
            }
        ],
    }


def _transport(registrations: list[dict[str, Any]]) -> httpx.MockTransport:
    """Hold every upload already and answer each registration with the card's id."""

    def handler(request: httpx.Request) -> httpx.Response:
        if request.url.path == "/v1/resources/uploads":
            return httpx.Response(200, json=payloads.UPLOAD_EXISTS)
        registrations.append(json.loads(request.content))
        return httpx.Response(200, json=_registered(CARD_ID))

    return httpx.MockTransport(handler)


def _plan_refs(registrations: list[dict[str, Any]]) -> list[list[dict[str, Any]]]:
    return [
        [ref for ref in body["activity"]["used"] if ref.get("role") == "plan"]
        for body in registrations
    ]


def test_a_live_plan_is_cited_by_its_own_request_and_every_later_one() -> None:
    registrations: list[dict[str, Any]] = []

    with (
        Bookshelf(BASE_URL, auth=None, transport=_transport(registrations)) as client,
        client.activity(kind="build", code_ref="test", config={}) as activity,
    ):
        activity.register(b"alpha", type="document", name="alpha")
        activity.register(b"method", type="document", name="method-card", role="plan")
        activity.register(b"beta", type="document", name="beta")

    assert _plan_refs(registrations) == [
        [],
        [{"resource_name": "method-card", "role": "plan"}],
        [{"tracking_id": CARD_ID, "role": "plan"}],
    ]


async def test_an_async_live_plan_is_cited_the_same_way() -> None:
    registrations: list[dict[str, Any]] = []

    async with (
        AsyncBookshelf(BASE_URL, auth=None, async_transport=_transport(registrations)) as client,
        client.activity(kind="build", code_ref="test", config={}) as activity,
    ):
        await activity.register(b"method", type="document", name="method-card", role="plan")
        await activity.register(b"beta", type="document", name="beta")

    assert _plan_refs(registrations) == [
        [{"resource_name": "method-card", "role": "plan"}],
        [{"tracking_id": CARD_ID, "role": "plan"}],
    ]


def test_a_live_plan_needs_a_name() -> None:
    with (
        Bookshelf(BASE_URL, auth=None, transport=_transport([])) as client,
        client.activity(kind="build", code_ref="test", config={}) as activity,
        pytest.raises(ValueError, match="plan needs a name"),
    ):
        activity.register(b"method", type="document", role="plan")


def test_a_plan_takes_no_inputs(tmp_path: Path) -> None:
    sink = RecordingSink(
        Bundle(tmp_path / "bundle"), Mock(spec=BookshelfClient), ContentCache(tmp_path / "cache")
    )
    forcing = sink.register_external(
        type="tabular", uri="https://example.invalid/forcing.csv", name="forcing"
    )
    with (
        sink.activity(code_ref="repo@sha", config={}) as activity,
        pytest.raises(ValueError, match="takes no used="),
    ):
        activity.register(
            b"method", type="document", name="method-card", role="plan", used=[forcing]
        )


def _edit_plan(bundle: Bundle, edit: str) -> None:
    """Break a recorded plan the way a hand edit of the manifest could."""
    card = next(resource for resource in bundle.manifest.resources if resource.role == "plan")
    if edit == "generated":
        card.generated = True
    elif edit == "used":
        card.used = ["forcing"]
    elif edit == "used_digests":
        card.used_digests = ["sha256:" + "0" * 64]
    else:
        bundle.manifest.activity = None
    bundle.write()


_EDITS = [
    ("generated", "uses nothing"),
    ("used", "uses nothing"),
    ("used_digests", "uses nothing"),
    ("no activity", "no activity"),
]


@pytest.mark.parametrize(("edit", "match"), _EDITS)
def test_replay_refuses_an_edited_plan_before_any_upload(
    tmp_path: Path, edit: str, match: str
) -> None:
    bundle = _record_plan_bundle(tmp_path)
    _edit_plan(bundle, edit)
    recorded: list[httpx.Request] = []

    with replay_client(recorded) as client, pytest.raises(InvalidBundleError, match=match):
        replay_bundle_sync(bundle.root, client)
    assert recorded == []


@pytest.mark.parametrize(("edit", "match"), _EDITS)
async def test_async_replay_refuses_an_edited_plan_before_any_upload(
    tmp_path: Path, edit: str, match: str
) -> None:
    bundle = _record_plan_bundle(tmp_path)
    _edit_plan(bundle, edit)
    recorded: list[httpx.Request] = []

    def handler(request: httpx.Request) -> httpx.Response:
        recorded.append(request)
        return httpx.Response(500)

    async with AsyncBookshelf(
        BASE_URL, auth=None, async_transport=httpx.MockTransport(handler)
    ) as client:
        with pytest.raises(InvalidBundleError, match=match):
            await replay_bundle(bundle.root, client)
    assert recorded == []


@pytest.mark.parametrize(("edit", "match"), _EDITS)
def test_validate_refuses_an_edited_plan(tmp_path: Path, edit: str, match: str) -> None:
    bundle = _record_plan_bundle(tmp_path)
    _edit_plan(bundle, edit)

    with pytest.raises(InvalidBundleError, match=match):
        Bundle.read(bundle.root).check_plans()


def test_a_recorded_plan_cannot_be_given_an_input(tmp_path: Path) -> None:
    bundle = _record_plan_bundle(tmp_path)

    with pytest.raises(ValueError, match="plan 'method-card' uses nothing"):
        bundle.add_used("method-card", "forcing")
