"""Contract tests for the committed generated Pydantic model core."""

import json
from pathlib import Path

import pydantic
import pytest

import bookshelf
from bookshelf import OPENAPI_VERSION, models
from bookshelf._generated import OPENAPI_VERSION as PRIVATE_OPENAPI_VERSION
from bookshelf._generated import models as private_models

SDK_ROOT = Path(__file__).resolve().parents[1]
GENERATED_ROOT = SDK_ROOT / "src" / "bookshelf" / "_generated"
HEADER = (
    "# DO NOT EDIT: generated by packages/bookshelf/scripts/generate_models.py.\n"
    "# Source: openapi.json\n"
    "# OPENAPI_VERSION: 0.1.0\n"
)


def test_root_and_private_imports_match() -> None:
    assert {"Bookshelf", "AsyncBookshelf", "Book", "BookEntry", "Resource"} <= set(
        bookshelf.__all__
    )
    assert models is private_models
    assert OPENAPI_VERSION == PRIVATE_OPENAPI_VERSION


def test_generated_tree_contract_and_markers() -> None:
    files = sorted(path.name for path in GENERATED_ROOT.iterdir() if path.is_file())
    assert files == ["__init__.py", "models.py"]
    assert all((GENERATED_ROOT / name).read_text().startswith(HEADER) for name in files)
    assert (SDK_ROOT / "src" / "bookshelf" / "py.typed").is_file()


def test_openapi_version_is_contract_provenance() -> None:
    contract = json.loads((SDK_ROOT / "openapi.json").read_text())
    assert OPENAPI_VERSION == contract["info"]["version"] == "0.1.0"
    assert not hasattr(bookshelf, "__version__")


def test_representative_generated_models_are_pydantic_v2_models() -> None:
    classes = [
        models.RegisterRequest,
        models.RegisterResourcesRequest,
        models.RegisterResourcesResponse,
        models.RegistrationEventsResponse,
        models.Problem,
        models.BookDraftRequest,
    ]
    assert all(issubclass(model, pydantic.BaseModel) for model in classes)
    assert pydantic.VERSION.startswith("2.")


def test_registration_contracts_validate_exact_payloads() -> None:
    assert models.RegisterRequest.model_validate({"type": "binary"})
    assert models.RegisterResourcesRequest.model_validate({"items": [{"type": "binary"}]})
    assert models.RegisterResourcesResponse.model_validate(
        {"activity_created": False, "atomic": True, "registered": []}
    )
    assert models.RegistrationEventsResponse.model_validate({"items": []})


def test_problem_and_book_draft_contracts() -> None:
    assert models.Problem.model_validate(
        {
            "type": "about:blank",
            "status": 400,
            "title": "Invalid request",
            "detail": "The request was invalid.",
        }
    )
    with pytest.raises(pydantic.ValidationError):
        models.BookDraftRequest.model_validate({"version": "", "series_name": "series"})

    request = models.BookDraftRequest.model_validate({"version": "v1", "series_name": "series"})
    assert request.visibility is models.Visibility.hidden
    assert isinstance(request.visibility, models.Visibility)
