[project]
name = "bookshelf"
version = "0.4.0"
description = "A collection of curated climate data sets"
readme = "README.md"
authors = [
    { name = "Jared Lewis", email = "jared.lewis@climate-resource.com" }
]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "scmdata>=0.16.1",
    "pooch",
    "pydantic>=1.10.17",
    "datapackage>=1.15.2",
    "pyyaml",
    "platformdirs>=4.3.6",
]

[tool.uv]
dev-dependencies = [
    "pytest>=7.3.1",
    "pytest-cov>=4.0.0",
    "pytest-mock>=3.11.1",
    "pytest-xdist>=3.3.1",
    "requests-mock>=1.11.0",
    "mypy>=1.2.0",
    "ruff>=0.1.8",
    "pre-commit>=3.3.1",
    "towncrier>=23.6.0",
    "liccheck>=0.9.1",
    # Stubs
    "types-pyyaml>=6.0.12.20240917",
    "boto3-stubs[essential]>=1.35.39",
    "types-requests>=2.32.0.20240914",
    "pandas-stubs>=2.2.3.241009",
    # Docs
    "mkdocs>=1.6.0",
    "mkdocstrings[python]>=0.25.0",
    "mkdocs-material>=9.5.0",
    "mkdocs-gen-files>=0.5.0",
    "mkdocs-section-index>=0.3.9",
    "mkdocs-literate-nav>=0.6.1",
    "mkdocs-autorefs>=1.0.1",
    "mkdocs-jupyter>=0.24.0",
    "myst-nb>=1.1.1",
    "jupyterlab>=4.2.0",
    "jupytext>=1.16.3",
    "matplotlib>=3.9.2",
    "mike>=2.1.3",
    "mkdocs-minify-plugin>=0.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.custom]
path = "hatch_build.py"
